# mam/my/counter/.github/workflows/deploy.yml
name: Deploy

on:
    workflow_dispatch:
    push:

jobs:
    build:
        
        runs-on: ubuntu-latest
        
        steps:

            - name: Build app
              uses: hyoo-ru/mam_build@master2
              with:
                  token: ${{ secrets.GH_PAT }}
                  package: 'my/counter'
                  meta: |
                      my https://github.com/SbWereWolf/mam_my

            - name: Deploy on GitHub Pages
              if: github.ref == 'refs/heads/main'
              uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
              with:
                  repo-token: ${{ secrets.GH_PAT }}
                  site-directory: 'my/counter/-'
